"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno con prioridad:
# 1) .env
# 2) .env.local (sobrescribe .env si existe)
env_file = BASE_DIR / ".env"
env_local_file = BASE_DIR / ".env.local"
if env_file.exists():
    load_dotenv(env_file)
if env_local_file.exists():
    load_dotenv(env_local_file, override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ValueError(
        "DJANGO_SECRET_KEY no está configurada. "
        "Define esta variable de entorno antes de iniciar la aplicación."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool( os.environ.get('DJANGO_DEBUG', True) )

ALLOWED_HOSTS = [
    'api.cincosas.com', 
    'www.api.cincosas.com', 
    '192.168.79.11', 
    '127.0.0.1', 
    'localhost'
]

# CORS: Solo permitir orígenes específicos (whitelist)
CORS_ALLOW_ALL_ORIGINS = False  # ✅ Seguridad mejorada
CORS_ALLOW_CREDENTIALS = True  # Permite envío de cookies entre dominios

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://frontend.cincosas.com",
    "https://www.frontend.cincosas.com",
]

CORS_EXPOSE_HEADERS = [
    "Content-Disposition",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://frontend.cincosas.com",
    "https://www.frontend.cincosas.com",
]

# Configuración de cookies seguras
SECURE_COOKIE = not DEBUG  # Solo HTTPS en producción
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True  # Protección XSS
CSRF_COOKIE_HTTPONLY = False  # Necesario para leer el token en el frontend

# SameSite='Strict' para máxima protección CSRF
SESSION_COOKIE_SAMESITE = 'Strict'
CSRF_COOKIE_SAMESITE = 'Lax'  # Lax para CSRF token (necesita ser leído por JS)

# Content Security Policy y security headers
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party
    "rest_framework",
    "corsheaders",
    'drf_spectacular',
    
    # Local apps
    'apps.authentication',
    'apps.common',
    'apps.security',
    'apps.operaciones',
    'apps.empleados',
    'apps.ia_dev',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "apps.security.authentication.api_key_authentication.APIKeyAuthentication",
        "apps.authentication.authentication.jwt_authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "apps.security.permissions.api_permissions.IsAuthenticatedOrAPIKey",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "apps.security.throttling.api_throttling.APIKeyRateThrottle",
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

LEGACY_JWT_SHARED_SECRET = os.environ.get('LEGACY_JWT_SHARED_SECRET', '')
LEGACY_JWT_ISSUER = os.environ.get('LEGACY_JWT_ISSUER', 'legacy-app')
LEGACY_JWT_AUDIENCE = os.environ.get('LEGACY_JWT_AUDIENCE', 'app-cinco')
LEGACY_JWT_LEEWAY_SECONDS = int(os.environ.get('LEGACY_JWT_LEEWAY_SECONDS', '30'))

SPECTACULAR_SETTINGS = {
    'TITLE': 'App Cinco API',
    'DESCRIPTION': 'Documentación de endpoints - App Cinco',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SECURITY': [
        {'ApiKeyAuth': []},
        {'BearerAuth': []},
    ],
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
    },
    'COMPONENTS': {
        'securitySchemes': {
            'ApiKeyAuth': {
                'type': 'apiKey',
                'in': 'header',
                'name': 'X-API-Key',
                'description': 'API Key para integraciones externas. Formato: cinco_xxxxx',
            },
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    }
}

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # },
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('BD_NAME', 'db_cincosas'),
        'USER': os.environ.get('BD_USER', 'root'),
        'PASSWORD': os.environ.get('BD_PASSWORD', ''),
        'HOST': os.environ.get('BD_HOST', '127.0.0.1'),
        'PORT': os.environ.get('BD_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        }
    },
    'azul': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_AZUL_NAME', 'cinco-api'),
        'USER': os.environ.get('DB_AZUL_USER', 'root'),
        'PASSWORD': os.environ.get('DB_AZUL_PASSWORD', ''),
        'HOST': os.environ.get('DB_AZUL_HOST', '127.0.0.1'),
        'PORT': os.environ.get('DB_AZUL_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        }
    },
    'logistica_cinco': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('LOGISTICA_DB_NAME', 'logistica_cinco'),
        'USER': os.environ.get('LOGISTICA_DB_USER', os.environ.get('BD_USER', 'root')),
        'PASSWORD': os.environ.get('LOGISTICA_DB_PASSWORD', os.environ.get('BD_PASSWORD', '')),
        'HOST': os.environ.get('LOGISTICA_DB_HOST', os.environ.get('BD_HOST', '127.0.0.1')),
        'PORT': os.environ.get('LOGISTICA_DB_PORT', os.environ.get('BD_PORT', '3306')),
        'OPTIONS': {
            'charset': 'utf8mb4',
        }
    }
}

DATABASE_ROUTERS = ['config.db_router.MultiDBRouter']


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-CO'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
# STATIC_URL = '/home/admcinco/app_cinco/backend/static/'
STATIC_URL = os.getenv('BASE_PATH', '') + 'static/'
# STATIC_ROOT = '/home/admcinco/app_cinco/backend/static'
STATIC_ROOT = os.getenv('BASE_PATH', '') + 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security headers (ya configurados arriba según DEBUG)
#SECURE_HSTS_SECONDS = 31536000
#SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True  # Solo si estás seguro de que todo es HTTPS
#SECURE_SSL_REDIRECT = True
#SESSION_COOKIE_SECURE = True
#CSRF_COOKIE_SECURE = True

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'security_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'security.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'security': {
            'handlers': ['console', 'security_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}
