# Generated by Django 5.2.10 on 2026-05-15 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ot', models.CharField(blank=True, default='', max_length=100)),
                ('ots', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('pausada', 'Pausada'), ('reprogramada', 'Reprogramada')], default='pendiente', max_length=20)),
                ('responsable_id', models.IntegerField()),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin_estimado', models.DateField(blank=True, null=True)),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'operaciones_actividades',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ActividadDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_trabajo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('extra', models.JSONField(blank=True, null=True)),
                ('actividad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='operaciones.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadResponsableSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado_id', models.IntegerField()),
                ('nombre', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=100)),
                ('carpeta', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('movil', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_snapshot', to='operaciones.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('coordenada_x', models.CharField(max_length=100)),
                ('coordenada_y', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=100)),
                ('nodo', models.CharField(max_length=100)),
                ('actividad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion', to='operaciones.actividad')),
            ],
        ),
    ]
