# Generated by Django 5.2.10 on 2026-05-15 20:10

import django.db.models.deletion
from django.db import migrations, models


def backfill_actividad_ots(apps, schema_editor):
    Actividad = apps.get_model('operaciones', 'Actividad')
    ActividadOT = apps.get_model('operaciones', 'ActividadOT')

    for actividad in Actividad.objects.all().iterator():
        raw_ots = actividad.ots or actividad.ot or ""
        values = []
        seen = set()
        for item in raw_ots.replace(",", "\n").split("\n"):
            ot = item.strip()
            if not ot or ot in seen:
                continue
            values.append(ot)
            seen.add(ot)

        for ot in values:
            ActividadOT.objects.get_or_create(
                ot=ot,
                defaults={
                    'actividad': actividad,
                    'is_active': True,
                    'created_by': actividad.created_by,
                    'updated_by': actividad.updated_by,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ot', models.CharField(db_index=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_relaciones', to='operaciones.actividad')),
            ],
            options={
                'db_table': 'operaciones_actividad_ots',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['ot', 'is_active'], name='operaciones_ot_is_a_e1d1cb_idx')],
            },
        ),
        migrations.RunPython(backfill_actividad_ots, migrations.RunPython.noop),
    ]
