# Generated by Django 5.2.10 on 2026-05-15 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_actividadot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='actividadot',
            new_name='operaciones_ot_7eb8d7_idx',
            old_name='operaciones_ot_is_a_e1d1cb_idx',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='ots',
        ),
    ]
