# Generated by Django 5.2.10 on 2026-05-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_rename_operaciones_ot_is_a_e1d1cb_idx_operaciones_ot_7eb8d7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadot',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividadot',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
