# Generated by Django 5.2.10 on 2026-05-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_actividadot_fecha_fin_actividadot_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividaddetalle',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='actividadubicacion',
            name='coordenada_x',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='actividadubicacion',
            name='coordenada_y',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='actividadubicacion',
            name='nodo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='actividadubicacion',
            name='zona',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
