from __future__ import annotations

from typing import Any


FUENTES_DD_GOBERNADAS = [
    "ai_dictionary.dd_sinonimos",
    "ai_dictionary.dd_reglas",
    "ai_dictionary.ia_dev_capacidades_columna",
]


def obtener_sinonimos_gobernados_inventario() -> list[dict[str, Any]]:
    filas: list[dict[str, Any]] = []

    def agregar(
        *,
        alias: str,
        canonico: str,
        scope_tipo: str,
        scope_clave: str,
        target_type: str,
        target_column: str = "",
    ) -> None:
        filas.append(
            {
                "synonym": alias,
                "canonical_value": canonico,
                "target_type": target_type,
                "target_table": "",
                "target_column": target_column,
                "domain_code": "inventario_logistica",
                "scope_tipo": scope_tipo,
                "scope_clave": scope_clave,
                "trace_tag": f"dd_sinonimos:{scope_clave}:{alias.lower()}",
                "source": "p3b_seed_inventario_logistica",
                "priority": 100,
                "activo": True,
            }
        )

    for alias in ("material claro", "material de claro"):
        agregar(
            alias=alias,
            canonico="material_claro",
            scope_tipo="familia",
            scope_clave="inventario.family.material_claro",
            target_type="material_family",
            target_column="tipo",
        )
    for alias in ("ferretero", "material ferretero", "ferreteria", "ferretería"):
        agregar(
            alias=alias,
            canonico="ferretero",
            scope_tipo="familia",
            scope_clave="inventario.family.ferretero",
            target_type="material_family",
            target_column="tipo",
        )
    agregar(
        alias="material",
        canonico="material_generico",
        scope_tipo="familia",
        scope_clave="inventario.family.material_generico",
        target_type="material_family",
        target_column="tipo",
    )
    for alias in ("cuadrilla", "brigada", "movil", "móvil"):
        agregar(
            alias=alias,
            canonico="movil",
            scope_tipo="entidad",
            scope_clave="inventario.entity.movil",
            target_type="entity",
            target_column="movil",
        )
    for alias in ("tecnico", "técnico", "empleado", "cedula", "cédula"):
        agregar(
            alias=alias,
            canonico="cedula",
            scope_tipo="entidad",
            scope_clave="inventario.entity.cedula",
            target_type="entity",
            target_column="cedula",
        )
    for alias in ("kardex", "movimientos", "entradas y salidas"):
        agregar(
            alias=alias,
            canonico="movement_history",
            scope_tipo="intencion",
            scope_clave="inventario.intent.movement_history",
            target_type="intent",
        )
    for alias in ("serial", "seriales", "equipo", "equipos", "cpe"):
        agregar(
            alias=alias,
            canonico="serializados",
            scope_tipo="familia",
            scope_clave="inventario.family.serializados",
            target_type="material_family",
            target_column="serial",
        )
    for alias in ("proveedor", "contratante", "archivo", "excel", "adjunto"):
        agregar(
            alias=alias,
            canonico="validacion_seriales_proveedor",
            scope_tipo="intencion",
            scope_clave=f"inventario.intent.provider_serial_validation.{alias.lower()}",
            target_type="intent",
        )
    for alias, canonico in (
        ("deco", "DECO"),
        ("decodificador", "DECO"),
        ("equipo deco", "DECO"),
        ("serializado deco", "DECO"),
        ("familia deco", "DECO"),
        ("cpe", "CPE"),
        ("equipo cpe", "CPE"),
        ("serializado cpe", "CPE"),
        ("familia cpe", "CPE"),
    ):
        agregar(
            alias=alias,
            canonico=canonico,
            scope_tipo="familia_serializada",
            scope_clave=f"inventario.serial_family.{alias.lower().replace(' ', '_')}",
            target_type="filter",
            target_column="familia",
        )
    agregar(
        alias="bodega",
        canonico="bodega",
        scope_tipo="entidad",
        scope_clave="inventario.entity.bodega",
        target_type="entity",
        target_column="bodega",
    )
    agregar(
        alias="operacion_hfc",
        canonico="operacion_hfc",
        scope_tipo="filtro",
        scope_clave="inventario.filter.operacion_hfc",
        target_type="filter",
        target_column="bodega",
    )
    return filas


def obtener_reglas_gobernadas_inventario() -> list[dict[str, Any]]:
    def regla(
        *,
        codigo: str,
        descripcion: str,
        rule_kind: str,
        priority: int,
        condition_json: dict[str, Any],
        result_json: dict[str, Any],
        intent: str = "",
        entity_field: str = "",
    ) -> dict[str, Any]:
        return {
            "rule_name": codigo,
            "codigo": codigo,
            "nombre": codigo,
            "description": descripcion,
            "rule_kind": rule_kind,
            "intent": intent,
            "entity_field": entity_field,
            "condition_json": condition_json,
            "result_json": result_json,
            "priority": priority,
            "migration_status": "governed",
            "trace_tag": f"dd_reglas:{codigo}",
            "source_table": "ai_dictionary.dd_reglas",
            "source": "p3b_seed_inventario_logistica",
            "is_fallback": False,
            "activo": True,
        }

    return [
        regla(
            codigo="inventario.identifier.numeric_to_cedula",
            descripcion="Identificador numerico operativo se interpreta como cedula.",
            rule_kind="identifier_resolution",
            priority=100,
            condition_json={"value_kind": "numeric", "min_len": 5},
            result_json={"field": "cedula", "entity_type": "empleado"},
        ),
        regla(
            codigo="inventario.identifier.alphanumeric_to_movil",
            descripcion="Identificador alfanumerico operativo se interpreta como movil o cuadrilla.",
            rule_kind="identifier_resolution",
            priority=95,
            condition_json={"value_kind": "alphanumeric", "must_have_letters": True, "must_have_digits": True},
            result_json={"field": "movil", "entity_type": "movil"},
        ),
        regla(
            codigo="inventario.filter.material_claro",
            descripcion="Material claro se filtra como tipo material.",
            rule_kind="filter_resolution",
            priority=100,
            condition_json={"family": "material_claro"},
            result_json={"tipo": "material"},
        ),
        regla(
            codigo="inventario.filter.ferretero",
            descripcion="Ferretero se filtra como tipo ferretero.",
            rule_kind="filter_resolution",
            priority=100,
            condition_json={"family": "ferretero"},
            result_json={"tipo": "ferretero"},
        ),
        regla(
            codigo="inventario.filter.material_generico",
            descripcion="Material generico incluye material claro y ferretero.",
            rule_kind="filter_resolution",
            priority=90,
            condition_json={"family": "material_generico"},
            result_json={"tipo": ["material", "ferretero"]},
        ),
        regla(
            codigo="inventario.serial_family.busqueda_parcial_catalogo",
            descripcion="La familia serializada se resuelve por coincidencia parcial gobernada sobre base_codigo_seriales.familia usando normalizacion upper/trim.",
            rule_kind="filter_resolution",
            priority=99,
            condition_json={
                "family": "serializados",
                "field": "material_family",
                "source_table": "logistica_cinco.base_codigo_seriales",
                "source_column": "familia",
                "match_mode": "contains",
                "normalization": ["upper", "trim"],
            },
            result_json={
                "filter_field": "material_family",
                "filter_match_mode": "contains",
                "catalog_table": "logistica_cinco.base_codigo_seriales",
                "catalog_column": "familia",
            },
        ),
        regla(
            codigo="inventario.scope.dual_block_unspecified_family",
            descripcion="Inventario generico por portador sin familia explicita devuelve bloque materiales y serializados.",
            rule_kind="scope_resolution",
            priority=90,
            condition_json={"intent": "stock_balance", "holder_scope_required": True, "tipo_absent": True},
            result_json={"include_serialized": True, "response_profile_override": "inventory.stock.mobile.dual_block"},
            intent="stock_balance",
        ),
        regla(
            codigo="inventario.metric.serial_count_only",
            descripcion="Serializados y equipos se manejan por conteo y no por cantidad.",
            rule_kind="metric_policy",
            priority=100,
            condition_json={"family": "serializados"},
            result_json={"quantity_mode": "count"},
        ),
        regla(
            codigo="inventario.metric.stock_include_zero_negative",
            descripcion="Los saldos de inventario incluyen positivos, cero y negativos.",
            rule_kind="stock_policy",
            priority=100,
            condition_json={"intent": "stock_balance"},
            result_json={
                "allow_positive": True,
                "allow_zero": True,
                "allow_negative": True,
                "forbidden_sql_filters": ["HAVING saldo > 0", "WHERE saldo > 0", "HAVING saldo <> 0"],
            },
            intent="stock_balance",
        ),
        regla(
            codigo="inventario.kardex.signos_operativos",
            descripcion="En kardex la entrega suma como entrada; devolucion, consumo y cobro restan como salida.",
            rule_kind="kardex_policy",
            priority=100,
            condition_json={"intent": "movement_history"},
            result_json={
                "entrada_movimientos": ["entrega"],
                "salida_movimientos": ["devolucion", "consumo", "cobro"],
                "saldo_acumulado_orden": ["fecha", "movimiento_id"],
            },
            intent="movement_history",
        ),
        regla(
            codigo="inventario.limit.document_generation_pending",
            descripcion="Actas, SAP y documentos quedan como limitacion declarada cuando no existe fuente gobernada.",
            rule_kind="limitation",
            priority=100,
            condition_json={"intent": "document_generation"},
            result_json={
                "template_id": "inventory_document_generation_pending",
                "candidate_capability": "inventory_document_generation_pending",
                "planner_route_hint": "inventory.document_generation.pending",
                "response_profile": "inventory.document_generation.pending",
                "expected_output": "document_generation_pending",
                "grain": "documento_pendiente",
                "columns": ["documento", "codigo", "serial", "fecha"],
                "known_limitations": ["documentos_sap_y_actas_no_habilitados"],
            },
            intent="document_generation",
        ),
        regla(
            codigo="inventario.limit.transfer_destination_missing_metadata",
            descripcion="Traslados por bodega destino quedan bloqueados mientras no exista metadata fisica segura.",
            rule_kind="limitation",
            priority=100,
            condition_json={"intent": "transfer_query", "group_by_contains": "bodega_destino"},
            result_json={
                "template_id": "inventory_transfer_destination_not_available",
                "candidate_capability": "",
                "planner_route_hint": "inventory.transfer.destination_unresolved",
                "response_profile": "inventory.transfer.destination.blocked",
                "expected_output": "saldo_inventario",
                "grain": "movimiento_por_fecha_y_codigo",
                "columns": ["codigo", "cantidad", "bodega"],
                "known_limitations": ["missing_physical_column:bodega_destino"],
            },
            intent="transfer_query",
        ),
        regla(
            codigo="inventario.route.kardex_employee",
            descripcion="Kardex por empleado o tecnico se resuelve por cedula.",
            rule_kind="binding",
            priority=100,
            condition_json={"intent": "movement_history", "field": "cedula"},
            result_json={
                "template_id": "inventory_kardex_by_employee",
                "candidate_capability": "inventory_kardex_by_employee",
                "planner_route_hint": "inventory.kardex.employee",
                "response_profile": "inventory.kardex.employee.detail",
                "expected_output": "kardex_operativo",
                "grain": "movimiento_por_codigo",
                "columns": [
                    "fecha",
                    "tipo_movimiento",
                    "codigo",
                    "descripcion",
                    "tipo",
                    "cedula",
                    "empleado",
                    "movil",
                    "estado_empleado",
                    "bodega",
                    "orden_trabajo",
                    "ticket",
                    "entrada",
                    "salida",
                    "cantidad",
                    "efecto",
                    "saldo_movimiento",
                ],
            },
            intent="movement_history",
            entity_field="cedula",
        ),
        regla(
            codigo="inventario.route.kardex_codigo",
            descripcion="Kardex consolidado se resuelve por codigo cuando no hay cedula.",
            rule_kind="binding",
            priority=90,
            condition_json={"intent": "movement_history", "field": "codigo", "forbid_field": "cedula"},
            result_json={
                "template_id": "inventory_kardex_consolidated",
                "candidate_capability": "inventory_kardex_consolidated",
                "planner_route_hint": "inventory.kardex.consolidated",
                "response_profile": "inventory.kardex.consolidated.detail",
                "expected_output": "kardex_operativo",
                "grain": "movimiento_por_fecha_y_codigo",
                "columns": ["fecha", "tipo_movimiento", "codigo", "cantidad", "origen", "destino"],
            },
            intent="movement_history",
            entity_field="codigo",
        ),
        regla(
            codigo="inventario.route.stock_balance_holder",
            descripcion="Inventario operativo por cedula o movil usa la ruta de saldo por portador.",
            rule_kind="binding",
            priority=85,
            condition_json={"intent": "stock_balance", "field_any_of": ["cedula", "movil"]},
            result_json={
                "template_id": "inventory_material_stock_mobile",
                "candidate_capability": "inventory_stock_balance_by_mobile",
                "planner_route_hint": "inventory.material_stock.mobile",
                "response_profile": "inventory.stock.mobile.detail",
                "expected_output": "saldo_inventario",
                "grain": "saldo_por_codigo",
                "columns": [
                    "codigo",
                    "descripcion",
                    "tipo",
                    "cedula",
                    "empleado",
                    "movil",
                    "estado_empleado",
                    "entregas",
                    "devoluciones",
                    "consumos",
                    "cobros",
                    "saldo",
                ],
            },
            intent="stock_balance",
        ),
        regla(
            codigo="inventario.route.serial_stock_family_grouped_dimension",
            descripcion="Saldo serializado por familia se agrega por movil, tecnico, cuadrilla o bodega usando catalogo gobernado.",
            rule_kind="binding",
            priority=98,
            condition_json={
                "intent": "stock_balance",
                "family": "serializados",
                "group_by_any_of": ["movil", "cedula", "bodega"],
                "filter_any_of": ["material_family"],
                "forbid_field_any_of": ["cedula", "movil", "serial"],
            },
            result_json={
                "template_id": "inventory_serial_stock_by_family_grouped_dimension",
                "candidate_capability": "inventory_serial_stock_by_family_grouped_dimension",
                "planner_route_hint": "inventory.serial_stock.family_dimension",
                "response_profile": "inventory.serial.stock.dimension.detail",
                "expected_output": "inventario_serializado",
                "grain": "saldo_serializado_por_dimension_y_codigo",
                "columns": [
                    "dimension",
                    "cedula",
                    "nombre",
                    "apellido",
                    "empleado",
                    "movil",
                    "estado_empleado",
                    "bodega",
                    "codigo",
                    "descripcion",
                    "familia",
                    "seriales_total",
                    "cedulas_asociadas",
                    "en_movil",
                    "en_base",
                    "cobros",
                    "saldo",
                ],
            },
            intent="stock_balance",
        ),
        regla(
            codigo="inventario.route.stock_balance_material_grouped_dimension",
            descripcion="Saldo o inventario de material filtrado por codigo, descripcion o familia se agrega por la dimension solicitada.",
            rule_kind="binding",
            priority=95,
            condition_json={
                "intent": "stock_balance",
                "group_by_any_of": ["movil", "cedula", "bodega"],
                "filter_any_of": ["codigo", "descripcion"],
                "forbid_field_any_of": ["cedula", "movil"],
            },
            result_json={
                "template_id": "inventory_material_stock_grouped_dimension",
                "candidate_capability": "inventory_stock_balance_by_material_dimension",
                "planner_route_hint": "inventory.material_stock.dimension",
                "response_profile": "inventory.stock.dimension.summary",
                "expected_output": "saldo_inventario",
                "grain": "saldo_por_dimension_y_codigo",
                "columns": [
                    "dimension",
                    "cedula",
                    "empleado",
                    "movil",
                    "bodega",
                    "codigo",
                    "descripcion",
                    "tipo",
                    "entregas",
                    "devoluciones",
                    "consumos",
                    "cobros",
                    "saldo",
                ],
            },
            intent="stock_balance",
        ),
        regla(
            codigo="inventario.route.serial_holder",
            descripcion="Inventario serializado por portador usa la ruta serializada dedicada.",
            rule_kind="binding",
            priority=95,
            condition_json={"intent": "serial_holder_query", "field_any_of": ["cedula", "movil", "serial"]},
            result_json={
                "template_id": "inventory_serial_by_operational_holder",
                "candidate_capability": "inventory_serial_by_operational_holder",
                "planner_route_hint": "inventory.serial.holder",
                "response_profile": "inventory.serial.holder.detail",
                "expected_output": "inventario_serializado",
                "grain": "serial_por_codigo_y_estado",
                "columns": ["serial", "codigo", "descripcion", "familia", "estado", "cedula", "movil", "saldo"],
            },
            intent="serial_holder_query",
        ),
        regla(
            codigo="inventario.route.provider_serial_validation",
            descripcion="Validacion de seriales externos de proveedor se resuelve como capability gobernada con archivo adjunto y consultas seguras.",
            rule_kind="binding",
            priority=99,
            condition_json={
                "intent": "provider_serial_validation",
                "requires_attachment": True,
            },
            result_json={
                "template_id": "inventory_provider_serial_validation",
                "candidate_capability": "inventory_provider_serial_validation",
                "planner_route_hint": "inventory.serial.validation.provider_file",
                "response_profile": "inventory.serial.validation.provider_file.detail",
                "expected_output": "validacion_seriales_proveedor",
                "grain": "serial_proveedor_validado",
                "columns": [
                    "fila_archivo",
                    "serial_proveedor",
                    "material_proveedor",
                    "denominacion_proveedor",
                    "familia_proveedor",
                    "encontrado",
                    "fuente",
                    "estado",
                    "estado_contiene_movil",
                    "movil_asociado",
                    "cedula_persona",
                    "nombre",
                    "apellido",
                    "empleado",
                    "bodega",
                    "codigo_interno",
                    "descripcion_interna",
                    "ultima_fecha_encontrada",
                    "duplicado_en_archivo",
                    "ocurrencias_archivo",
                    "solo_historico",
                    "fuentes_coincidencia",
                    "tablas_consultadas",
                    "tablas_historicas_no_existian",
                    "observacion_operativa",
                ],
                "known_limitations": ["attachment_required", "provider_file_empty", "serial_column_not_detected"],
            },
            intent="provider_serial_validation",
        ),
    ]


def obtener_capacidades_columna_inventario() -> list[dict[str, Any]]:
    def capacidad(
        *,
        campo_logico: str,
        table_name: str,
        column_name: str,
        supports_filter: bool,
        supports_group_by: bool,
        supports_metric: bool,
        is_identifier: bool,
        is_date: bool = False,
        capabilities_compatibles: list[str] | None = None,
    ) -> dict[str, Any]:
        return {
            "domain_code": "inventario_logistica",
            "dominio_aplicable": "inventario_logistica",
            "campo_logico": campo_logico,
            "table_name": table_name,
            "column_name": column_name,
            "supports_filter": supports_filter,
            "supports_group_by": supports_group_by,
            "supports_metric": supports_metric,
            "supports_dimension": supports_group_by,
            "is_date": is_date,
            "is_identifier": is_identifier,
            "is_chart_dimension": supports_group_by,
            "is_chart_measure": supports_metric,
            "normalization_strategy": "inventory_governed_metadata_p3b",
            "priority": 90,
            "active": True,
            "capabilities_compatibles": list(capabilities_compatibles or []),
            "trace_tag": f"ia_dev_capacidades_columna:{campo_logico}",
            "source": "p3b_seed_inventario_logistica",
        }

    return [
        capacidad(
            campo_logico="cedula",
            table_name="cinco_base_de_personal",
            column_name="cedula",
            supports_filter=True,
            supports_group_by=True,
            supports_metric=False,
            is_identifier=True,
            capabilities_compatibles=[
                "inventory_stock_balance_by_mobile",
                "inventory_kardex_by_employee",
                "inventory_serial_stock_by_family_grouped_dimension",
            ],
        ),
        capacidad(
            campo_logico="movil",
            table_name="cinco_base_de_personal",
            column_name="movil",
            supports_filter=True,
            supports_group_by=True,
            supports_metric=False,
            is_identifier=True,
            capabilities_compatibles=[
                "inventory_stock_balance_by_mobile",
                "inventory_serial_by_operational_holder",
                "inventory_serial_stock_by_family_grouped_dimension",
            ],
        ),
        capacidad(
            campo_logico="codigo",
            table_name="base_codigos",
            column_name="codigo",
            supports_filter=True,
            supports_group_by=True,
            supports_metric=False,
            is_identifier=True,
            capabilities_compatibles=[
                "inventory_kardex_consolidated",
                "inventory_stock_balance_by_mobile",
                "inventory_stock_balance_by_material_dimension",
            ],
        ),
        capacidad(
            campo_logico="serial",
            table_name="logistica_base_seriales",
            column_name="serial",
            supports_filter=True,
            supports_group_by=True,
            supports_metric=False,
            is_identifier=True,
            capabilities_compatibles=["inventory_serial_by_operational_holder", "inventory_traceability_by_serial"],
        ),
        capacidad(
            campo_logico="bodega",
            table_name="logistica_movimientos_entrega",
            column_name="bodega",
            supports_filter=True,
            supports_group_by=True,
            supports_metric=False,
            is_identifier=False,
            capabilities_compatibles=[
                "inventory_stock_balance_by_warehouse",
                "inventory_stock_balance_by_material_dimension",
                "inventory_serial_stock_by_family_grouped_dimension",
            ],
        ),
        capacidad(
            campo_logico="tipo",
            table_name="base_codigos",
            column_name="tipo",
            supports_filter=True,
            supports_group_by=True,
            supports_metric=False,
            is_identifier=False,
            capabilities_compatibles=[
                "inventory_stock_balance_by_mobile",
                "inventory_kardex_by_employee",
                "inventory_stock_balance_by_material_dimension",
            ],
        ),
        capacidad(
            campo_logico="estado",
            table_name="logistica_base_seriales",
            column_name="estado",
            supports_filter=True,
            supports_group_by=True,
            supports_metric=False,
            is_identifier=False,
            capabilities_compatibles=[
                "inventory_serial_by_operational_holder",
                "inventory_traceability_by_serial",
                "inventory_serial_stock_by_family_grouped_dimension",
            ],
        ),
        capacidad(
            campo_logico="fecha",
            table_name="logistica_movimientos_entrega",
            column_name="f_consumo",
            supports_filter=True,
            supports_group_by=True,
            supports_metric=False,
            is_identifier=False,
            is_date=True,
            capabilities_compatibles=["inventory_kardex_by_employee", "inventory_kardex_consolidated"],
        ),
        capacidad(
            campo_logico="orden_trabajo",
            table_name="logistica_movimientos_consumo",
            column_name="orden_trabajo",
            supports_filter=True,
            supports_group_by=True,
            supports_metric=False,
            is_identifier=False,
            capabilities_compatibles=["inventory_kardex_by_employee", "inventory_consumption_billing_operacion_hfc"],
        ),
        capacidad(
            campo_logico="familia",
            table_name="base_codigo_seriales",
            column_name="familia",
            supports_filter=True,
            supports_group_by=True,
            supports_metric=False,
            is_identifier=False,
            capabilities_compatibles=[
                "inventory_serial_by_operational_holder",
                "inventory_traceability_by_serial",
                "inventory_serial_stock_by_family_grouped_dimension",
            ],
        ),
        capacidad(
            campo_logico="descripcion",
            table_name="base_codigos",
            column_name="descripcion",
            supports_filter=True,
            supports_group_by=True,
            supports_metric=False,
            is_identifier=False,
            capabilities_compatibles=[
                "inventory_stock_balance_by_mobile",
                "inventory_kardex_consolidated",
                "inventory_stock_balance_by_material_dimension",
            ],
        ),
    ]


def construir_metadata_gobernada_inventario() -> dict[str, Any]:
    return {
        "dd_sinonimos": obtener_sinonimos_gobernados_inventario(),
        "dd_reglas": obtener_reglas_gobernadas_inventario(),
        "ia_dev_capacidades_columna": obtener_capacidades_columna_inventario(),
        "fuentes_dd": list(FUENTES_DD_GOBERNADAS),
    }
